# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from policy.v2 import policy_pb2 as policy_dot_v2_dot_policy__pb2


class PolicyServiceStub(object):
    """=============================================================================
    Service
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePolicy = channel.unary_unary(
                '/barndoor.policy.v2.PolicyService/CreatePolicy',
                request_serializer=policy_dot_v2_dot_policy__pb2.CreatePolicyRequest.SerializeToString,
                response_deserializer=policy_dot_v2_dot_policy__pb2.CreatePolicyResponse.FromString,
                _registered_method=True)
        self.GetPolicy = channel.unary_unary(
                '/barndoor.policy.v2.PolicyService/GetPolicy',
                request_serializer=policy_dot_v2_dot_policy__pb2.GetPolicyRequest.SerializeToString,
                response_deserializer=policy_dot_v2_dot_policy__pb2.GetPolicyResponse.FromString,
                _registered_method=True)
        self.UpdatePolicy = channel.unary_unary(
                '/barndoor.policy.v2.PolicyService/UpdatePolicy',
                request_serializer=policy_dot_v2_dot_policy__pb2.UpdatePolicyRequest.SerializeToString,
                response_deserializer=policy_dot_v2_dot_policy__pb2.UpdatePolicyResponse.FromString,
                _registered_method=True)
        self.ListPolicies = channel.unary_unary(
                '/barndoor.policy.v2.PolicyService/ListPolicies',
                request_serializer=policy_dot_v2_dot_policy__pb2.ListPoliciesRequest.SerializeToString,
                response_deserializer=policy_dot_v2_dot_policy__pb2.ListPoliciesResponse.FromString,
                _registered_method=True)
        self.ClonePolicy = channel.unary_unary(
                '/barndoor.policy.v2.PolicyService/ClonePolicy',
                request_serializer=policy_dot_v2_dot_policy__pb2.ClonePolicyRequest.SerializeToString,
                response_deserializer=policy_dot_v2_dot_policy__pb2.ClonePolicyResponse.FromString,
                _registered_method=True)
        self.GetPoliciesSummary = channel.unary_unary(
                '/barndoor.policy.v2.PolicyService/GetPoliciesSummary',
                request_serializer=policy_dot_v2_dot_policy__pb2.GetPoliciesSummaryRequest.SerializeToString,
                response_deserializer=policy_dot_v2_dot_policy__pb2.GetPoliciesSummaryResponse.FromString,
                _registered_method=True)
        self.GetFilterDefinitions = channel.unary_unary(
                '/barndoor.policy.v2.PolicyService/GetFilterDefinitions',
                request_serializer=policy_dot_v2_dot_policy__pb2.GetFilterDefinitionsRequest.SerializeToString,
                response_deserializer=policy_dot_v2_dot_policy__pb2.GetFilterDefinitionsResponse.FromString,
                _registered_method=True)
        self.ListPolicyRevisions = channel.unary_unary(
                '/barndoor.policy.v2.PolicyService/ListPolicyRevisions',
                request_serializer=policy_dot_v2_dot_policy__pb2.ListPolicyRevisionsRequest.SerializeToString,
                response_deserializer=policy_dot_v2_dot_policy__pb2.ListPolicyRevisionsResponse.FromString,
                _registered_method=True)
        self.ValidatePolicy = channel.unary_unary(
                '/barndoor.policy.v2.PolicyService/ValidatePolicy',
                request_serializer=policy_dot_v2_dot_policy__pb2.ValidatePolicyRequest.SerializeToString,
                response_deserializer=policy_dot_v2_dot_policy__pb2.ValidatePolicyResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/barndoor.policy.v2.PolicyService/HealthCheck',
                request_serializer=policy_dot_v2_dot_policy__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=policy_dot_v2_dot_policy__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PolicyServiceServicer(object):
    """=============================================================================
    Service
    =============================================================================

    """

    def CreatePolicy(self, request, context):
        """Create a new policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicy(self, request, context):
        """Get a policy by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicy(self, request, context):
        """Update an existing policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicies(self, request, context):
        """List policies with pagination, search, and filtering.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClonePolicy(self, request, context):
        """Clone an existing policy with " Copy" appended to the name and DRAFT status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoliciesSummary(self, request, context):
        """Get summary counts of policies by status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFilterDefinitions(self, request, context):
        """Get filter definitions for the policies list UI.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicyRevisions(self, request, context):
        """List all revisions for a policy with pagination.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidatePolicy(self, request, context):
        """Validate a policy before creation or update.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePolicy,
                    request_deserializer=policy_dot_v2_dot_policy__pb2.CreatePolicyRequest.FromString,
                    response_serializer=policy_dot_v2_dot_policy__pb2.CreatePolicyResponse.SerializeToString,
            ),
            'GetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicy,
                    request_deserializer=policy_dot_v2_dot_policy__pb2.GetPolicyRequest.FromString,
                    response_serializer=policy_dot_v2_dot_policy__pb2.GetPolicyResponse.SerializeToString,
            ),
            'UpdatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicy,
                    request_deserializer=policy_dot_v2_dot_policy__pb2.UpdatePolicyRequest.FromString,
                    response_serializer=policy_dot_v2_dot_policy__pb2.UpdatePolicyResponse.SerializeToString,
            ),
            'ListPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicies,
                    request_deserializer=policy_dot_v2_dot_policy__pb2.ListPoliciesRequest.FromString,
                    response_serializer=policy_dot_v2_dot_policy__pb2.ListPoliciesResponse.SerializeToString,
            ),
            'ClonePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ClonePolicy,
                    request_deserializer=policy_dot_v2_dot_policy__pb2.ClonePolicyRequest.FromString,
                    response_serializer=policy_dot_v2_dot_policy__pb2.ClonePolicyResponse.SerializeToString,
            ),
            'GetPoliciesSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoliciesSummary,
                    request_deserializer=policy_dot_v2_dot_policy__pb2.GetPoliciesSummaryRequest.FromString,
                    response_serializer=policy_dot_v2_dot_policy__pb2.GetPoliciesSummaryResponse.SerializeToString,
            ),
            'GetFilterDefinitions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFilterDefinitions,
                    request_deserializer=policy_dot_v2_dot_policy__pb2.GetFilterDefinitionsRequest.FromString,
                    response_serializer=policy_dot_v2_dot_policy__pb2.GetFilterDefinitionsResponse.SerializeToString,
            ),
            'ListPolicyRevisions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicyRevisions,
                    request_deserializer=policy_dot_v2_dot_policy__pb2.ListPolicyRevisionsRequest.FromString,
                    response_serializer=policy_dot_v2_dot_policy__pb2.ListPolicyRevisionsResponse.SerializeToString,
            ),
            'ValidatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePolicy,
                    request_deserializer=policy_dot_v2_dot_policy__pb2.ValidatePolicyRequest.FromString,
                    response_serializer=policy_dot_v2_dot_policy__pb2.ValidatePolicyResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=policy_dot_v2_dot_policy__pb2.HealthCheckRequest.FromString,
                    response_serializer=policy_dot_v2_dot_policy__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'barndoor.policy.v2.PolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('barndoor.policy.v2.PolicyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyService(object):
    """=============================================================================
    Service
    =============================================================================

    """

    @staticmethod
    def CreatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v2.PolicyService/CreatePolicy',
            policy_dot_v2_dot_policy__pb2.CreatePolicyRequest.SerializeToString,
            policy_dot_v2_dot_policy__pb2.CreatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v2.PolicyService/GetPolicy',
            policy_dot_v2_dot_policy__pb2.GetPolicyRequest.SerializeToString,
            policy_dot_v2_dot_policy__pb2.GetPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v2.PolicyService/UpdatePolicy',
            policy_dot_v2_dot_policy__pb2.UpdatePolicyRequest.SerializeToString,
            policy_dot_v2_dot_policy__pb2.UpdatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v2.PolicyService/ListPolicies',
            policy_dot_v2_dot_policy__pb2.ListPoliciesRequest.SerializeToString,
            policy_dot_v2_dot_policy__pb2.ListPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClonePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v2.PolicyService/ClonePolicy',
            policy_dot_v2_dot_policy__pb2.ClonePolicyRequest.SerializeToString,
            policy_dot_v2_dot_policy__pb2.ClonePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoliciesSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v2.PolicyService/GetPoliciesSummary',
            policy_dot_v2_dot_policy__pb2.GetPoliciesSummaryRequest.SerializeToString,
            policy_dot_v2_dot_policy__pb2.GetPoliciesSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFilterDefinitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v2.PolicyService/GetFilterDefinitions',
            policy_dot_v2_dot_policy__pb2.GetFilterDefinitionsRequest.SerializeToString,
            policy_dot_v2_dot_policy__pb2.GetFilterDefinitionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPolicyRevisions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v2.PolicyService/ListPolicyRevisions',
            policy_dot_v2_dot_policy__pb2.ListPolicyRevisionsRequest.SerializeToString,
            policy_dot_v2_dot_policy__pb2.ListPolicyRevisionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v2.PolicyService/ValidatePolicy',
            policy_dot_v2_dot_policy__pb2.ValidatePolicyRequest.SerializeToString,
            policy_dot_v2_dot_policy__pb2.ValidatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v2.PolicyService/HealthCheck',
            policy_dot_v2_dot_policy__pb2.HealthCheckRequest.SerializeToString,
            policy_dot_v2_dot_policy__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
