# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from policy.v1 import policy_pb2 as policy_dot_v1_dot_policy__pb2


class PolicyServiceStub(object):
    """=============================================================================
    Service
    =============================================================================

    Raw Cerbos policy management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishCerbosPolicy = channel.unary_unary(
                '/barndoor.policy.v1.PolicyService/PublishCerbosPolicy',
                request_serializer=policy_dot_v1_dot_policy__pb2.PublishCerbosPolicyRequest.SerializeToString,
                response_deserializer=policy_dot_v1_dot_policy__pb2.PublishCerbosPolicyResponse.FromString,
                _registered_method=True)
        self.GetCerbosPolicy = channel.unary_unary(
                '/barndoor.policy.v1.PolicyService/GetCerbosPolicy',
                request_serializer=policy_dot_v1_dot_policy__pb2.GetCerbosPolicyRequest.SerializeToString,
                response_deserializer=policy_dot_v1_dot_policy__pb2.GetCerbosPolicyResponse.FromString,
                _registered_method=True)
        self.ListCerbosPolicies = channel.unary_unary(
                '/barndoor.policy.v1.PolicyService/ListCerbosPolicies',
                request_serializer=policy_dot_v1_dot_policy__pb2.ListCerbosPoliciesRequest.SerializeToString,
                response_deserializer=policy_dot_v1_dot_policy__pb2.ListCerbosPoliciesResponse.FromString,
                _registered_method=True)
        self.EnableCerbosPolicy = channel.unary_unary(
                '/barndoor.policy.v1.PolicyService/EnableCerbosPolicy',
                request_serializer=policy_dot_v1_dot_policy__pb2.EnableCerbosPolicyRequest.SerializeToString,
                response_deserializer=policy_dot_v1_dot_policy__pb2.EnableCerbosPolicyResponse.FromString,
                _registered_method=True)
        self.DisableCerbosPolicy = channel.unary_unary(
                '/barndoor.policy.v1.PolicyService/DisableCerbosPolicy',
                request_serializer=policy_dot_v1_dot_policy__pb2.DisableCerbosPolicyRequest.SerializeToString,
                response_deserializer=policy_dot_v1_dot_policy__pb2.DisableCerbosPolicyResponse.FromString,
                _registered_method=True)
        self.EnableRestriction = channel.unary_unary(
                '/barndoor.policy.v1.PolicyService/EnableRestriction',
                request_serializer=policy_dot_v1_dot_policy__pb2.EnableRestrictionRequest.SerializeToString,
                response_deserializer=policy_dot_v1_dot_policy__pb2.EnableRestrictionResponse.FromString,
                _registered_method=True)
        self.DisableRestriction = channel.unary_unary(
                '/barndoor.policy.v1.PolicyService/DisableRestriction',
                request_serializer=policy_dot_v1_dot_policy__pb2.DisableRestrictionRequest.SerializeToString,
                response_deserializer=policy_dot_v1_dot_policy__pb2.DisableRestrictionResponse.FromString,
                _registered_method=True)
        self.ReloadCerbosCache = channel.unary_unary(
                '/barndoor.policy.v1.PolicyService/ReloadCerbosCache',
                request_serializer=policy_dot_v1_dot_policy__pb2.ReloadCerbosCacheRequest.SerializeToString,
                response_deserializer=policy_dot_v1_dot_policy__pb2.ReloadCerbosCacheResponse.FromString,
                _registered_method=True)
        self.CheckToolAccess = channel.unary_unary(
                '/barndoor.policy.v1.PolicyService/CheckToolAccess',
                request_serializer=policy_dot_v1_dot_policy__pb2.CheckToolAccessRequest.SerializeToString,
                response_deserializer=policy_dot_v1_dot_policy__pb2.CheckToolAccessResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/barndoor.policy.v1.PolicyService/HealthCheck',
                request_serializer=policy_dot_v1_dot_policy__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=policy_dot_v1_dot_policy__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class PolicyServiceServicer(object):
    """=============================================================================
    Service
    =============================================================================

    Raw Cerbos policy management
    """

    def PublishCerbosPolicy(self, request, context):
        """Publish a raw Cerbos policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCerbosPolicy(self, request, context):
        """Get raw Cerbos policies by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCerbosPolicies(self, request, context):
        """List raw Cerbos policies with optional filtering.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableCerbosPolicy(self, request, context):
        """Enable Cerbos policies by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableCerbosPolicy(self, request, context):
        """Disable Cerbos policies by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnableRestriction(self, request, context):
        """Enable a restriction by name for the given policy IDs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableRestriction(self, request, context):
        """Disable a restriction by name for the given policy IDs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadCerbosCache(self, request, context):
        """Trigger all Cerbos pods to reload their policy cache from the database.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckToolAccess(self, request, context):
        """Runtime

        Evaluate tool access policies via Cerbos and record audit events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health

        Health check endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishCerbosPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishCerbosPolicy,
                    request_deserializer=policy_dot_v1_dot_policy__pb2.PublishCerbosPolicyRequest.FromString,
                    response_serializer=policy_dot_v1_dot_policy__pb2.PublishCerbosPolicyResponse.SerializeToString,
            ),
            'GetCerbosPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCerbosPolicy,
                    request_deserializer=policy_dot_v1_dot_policy__pb2.GetCerbosPolicyRequest.FromString,
                    response_serializer=policy_dot_v1_dot_policy__pb2.GetCerbosPolicyResponse.SerializeToString,
            ),
            'ListCerbosPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCerbosPolicies,
                    request_deserializer=policy_dot_v1_dot_policy__pb2.ListCerbosPoliciesRequest.FromString,
                    response_serializer=policy_dot_v1_dot_policy__pb2.ListCerbosPoliciesResponse.SerializeToString,
            ),
            'EnableCerbosPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableCerbosPolicy,
                    request_deserializer=policy_dot_v1_dot_policy__pb2.EnableCerbosPolicyRequest.FromString,
                    response_serializer=policy_dot_v1_dot_policy__pb2.EnableCerbosPolicyResponse.SerializeToString,
            ),
            'DisableCerbosPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableCerbosPolicy,
                    request_deserializer=policy_dot_v1_dot_policy__pb2.DisableCerbosPolicyRequest.FromString,
                    response_serializer=policy_dot_v1_dot_policy__pb2.DisableCerbosPolicyResponse.SerializeToString,
            ),
            'EnableRestriction': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableRestriction,
                    request_deserializer=policy_dot_v1_dot_policy__pb2.EnableRestrictionRequest.FromString,
                    response_serializer=policy_dot_v1_dot_policy__pb2.EnableRestrictionResponse.SerializeToString,
            ),
            'DisableRestriction': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableRestriction,
                    request_deserializer=policy_dot_v1_dot_policy__pb2.DisableRestrictionRequest.FromString,
                    response_serializer=policy_dot_v1_dot_policy__pb2.DisableRestrictionResponse.SerializeToString,
            ),
            'ReloadCerbosCache': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadCerbosCache,
                    request_deserializer=policy_dot_v1_dot_policy__pb2.ReloadCerbosCacheRequest.FromString,
                    response_serializer=policy_dot_v1_dot_policy__pb2.ReloadCerbosCacheResponse.SerializeToString,
            ),
            'CheckToolAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckToolAccess,
                    request_deserializer=policy_dot_v1_dot_policy__pb2.CheckToolAccessRequest.FromString,
                    response_serializer=policy_dot_v1_dot_policy__pb2.CheckToolAccessResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=policy_dot_v1_dot_policy__pb2.HealthCheckRequest.FromString,
                    response_serializer=policy_dot_v1_dot_policy__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'barndoor.policy.v1.PolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('barndoor.policy.v1.PolicyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyService(object):
    """=============================================================================
    Service
    =============================================================================

    Raw Cerbos policy management
    """

    @staticmethod
    def PublishCerbosPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v1.PolicyService/PublishCerbosPolicy',
            policy_dot_v1_dot_policy__pb2.PublishCerbosPolicyRequest.SerializeToString,
            policy_dot_v1_dot_policy__pb2.PublishCerbosPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCerbosPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v1.PolicyService/GetCerbosPolicy',
            policy_dot_v1_dot_policy__pb2.GetCerbosPolicyRequest.SerializeToString,
            policy_dot_v1_dot_policy__pb2.GetCerbosPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCerbosPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v1.PolicyService/ListCerbosPolicies',
            policy_dot_v1_dot_policy__pb2.ListCerbosPoliciesRequest.SerializeToString,
            policy_dot_v1_dot_policy__pb2.ListCerbosPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableCerbosPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v1.PolicyService/EnableCerbosPolicy',
            policy_dot_v1_dot_policy__pb2.EnableCerbosPolicyRequest.SerializeToString,
            policy_dot_v1_dot_policy__pb2.EnableCerbosPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableCerbosPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v1.PolicyService/DisableCerbosPolicy',
            policy_dot_v1_dot_policy__pb2.DisableCerbosPolicyRequest.SerializeToString,
            policy_dot_v1_dot_policy__pb2.DisableCerbosPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnableRestriction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v1.PolicyService/EnableRestriction',
            policy_dot_v1_dot_policy__pb2.EnableRestrictionRequest.SerializeToString,
            policy_dot_v1_dot_policy__pb2.EnableRestrictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableRestriction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v1.PolicyService/DisableRestriction',
            policy_dot_v1_dot_policy__pb2.DisableRestrictionRequest.SerializeToString,
            policy_dot_v1_dot_policy__pb2.DisableRestrictionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadCerbosCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v1.PolicyService/ReloadCerbosCache',
            policy_dot_v1_dot_policy__pb2.ReloadCerbosCacheRequest.SerializeToString,
            policy_dot_v1_dot_policy__pb2.ReloadCerbosCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckToolAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v1.PolicyService/CheckToolAccess',
            policy_dot_v1_dot_policy__pb2.CheckToolAccessRequest.SerializeToString,
            policy_dot_v1_dot_policy__pb2.CheckToolAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/barndoor.policy.v1.PolicyService/HealthCheck',
            policy_dot_v1_dot_policy__pb2.HealthCheckRequest.SerializeToString,
            policy_dot_v1_dot_policy__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
